### ISSUE TITLE
CDIRをインストールしておくメディアと、データの保存先は同じである必要がありますか？

### ISSUE THREAD

**Issue by hmatrjp** [CyberDefenseInstitute/CDIR#1]
@IT に掲載されていた記事を読んでの質問です。
http://www.atmarkit.co.jp/ait/articles/1609/15/news006_2.html

「書き込み可能状態の USBメモリスティックに CDIR をインストールしておいて、それを
　ウィルスに感染しているかもしれない調査対応のPCに挿す」ことに抵抗を覚えます。

例えば CD-R から CDIR を起動し、別の書き込み可能なメディアをデータの保存先として指定することは可能なのでしょうか？

**Comment by 4n6ist** [comment]
コメントありがとうございます。おっしゃる通り現在のCDIR Collectorは、出力データを実行プログラムと同じ場所に保存することを前提にしています。

詳しくないユーザでも簡単に使えることを踏まえて作っているという経緯があるのですが、おっしゃる通りUSBデバイスが侵害の対象になってしまう、という懸念はありますので、ユーザ側で出力先を指定した場合はその設定を優先するような処理を検討したいと思います。

**Comment by hmatrjp** [comment]
回答ありがとうございました。
疑問の答えが得られましたので、Close します。
