### ISSUE TITLE
一部環境でのエラー発生時処理について

### ISSUE THREAD

**Issue by sa10a24** [CyberDefenseInstitute/CDIR#3]
Windows10の一部環境でcdir-collector.exeを実行した際、イベントログ取得時にエラーが発生し異常終了します。
以下のStealthOpenFileでエラーが発生した際にexitしているため、強制終了しているようです。
returnに修正することで、エラーが発生した場合でも以降のファイル取得は試行されるようになるかと思いますので、修正をご検討ください。
こちらの手元では以下の修正で他ファイルの取得が継続して試行されることを確認しました。
以上、よろしくお願いいたします。

CDIR/CDIR.cpp
```
@@ -231,7 +231,7 @@ int StealthGetFile(char *filepath, char *outpath, ostringstream *osslog = NULL,
  	FileInfo_t *file;
  	if ((file = StealthOpenFile(filepath)) == NULL) {
  		fprintf(stderr, "could not open file: %s\n", filepath);
 -		__exit(EXIT_FAILURE);
 +		return -1;
  	};
```

**Comment by 4n6ist** [comment]
@sa10a24 さん

報告&改善案ありがとうございます!!
記憶が曖昧ですが、こちらでも同様の事象に遭遇していたかもしれません。

いただいた修正は他に支障のないと思いますので、なるべく早く反映したいと思います。

**Comment by sa10a24** [comment]
よろしくお願いします。
Windows10の全く同じバージョン(winver)でも発生する端末としない端末があり、原因の特定はできていませんが、とりあえずの暫定措置です。。。

**Comment by 4n6ist** [comment]
遅くなってしまいましたが、こちらの件を反映して1.2.2としました。
引き続きPRいただいている件は検討進めます。
